# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x04user\"_\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x14\n\x0cphone_number\x18\x04 \x01(\t\x12\x11\n\tis_active\x18\x05 \x01(\x08\"`\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x14\n\x0cphone_number\x18\x04 \x01(\t\x12\x11\n\tis_active\x18\x05 \x01(\x08\"-\n\x08UserList\x12!\n\x05users\x18\x01 \x03(\x0b\x32\x12.user.UserResponse\"\x07\n\x05\x45mpty2\x88\x02\n\x0bUserService\x12\x30\n\x07GetUser\x12\x11.user.UserRequest\x1a\x12.user.UserResponse\x12\x33\n\nCreateUser\x12\x11.user.UserRequest\x1a\x12.user.UserResponse\x12\x33\n\nUpdateUser\x12\x11.user.UserRequest\x1a\x12.user.UserResponse\x12\x33\n\nDeleteUser\x12\x11.user.UserRequest\x1a\x12.user.UserResponse\x12(\n\tListUsers\x12\x0b.user.Empty\x1a\x0e.user.UserListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=23
  _globals['_USERREQUEST']._serialized_end=118
  _globals['_USERRESPONSE']._serialized_start=120
  _globals['_USERRESPONSE']._serialized_end=216
  _globals['_USERLIST']._serialized_start=218
  _globals['_USERLIST']._serialized_end=263
  _globals['_EMPTY']._serialized_start=265
  _globals['_EMPTY']._serialized_end=272
  _globals['_USERSERVICE']._serialized_start=275
  _globals['_USERSERVICE']._serialized_end=539
# @@protoc_insertion_point(module_scope)
